FROM resnostyle/base
MAINTAINER bwp.pearson@gmail.com

RUN 
    apt-get install -qy wget 
    apt-get -y clean && \
    

#VOLUME /config
#VOLUME /data

#EXPOSE 8081


#https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
